version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim:1.0.4-alpine
    steps:
      - run: echo 'export PATH=~/.nimble/bin:$PATH' >> $BASH_ENV
      - checkout
      # Reuse cached directories
      - restore_cache:
          key: nim-0000
      - run: nimble update -y
      - save_cache:
          key: nim-0000
          paths:
            - .nimble
      - run: nim -v
      - run: nimble -v
      - run: nimble check
      - run: nimble test
      - run: nimble check_style
      - run: nimble document
      - run: nimble install
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
